//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5466
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Accounting.MultiLanguages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangEN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traffic_Accounting.MultiLanguages.LangEN", typeof(LangEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0 build 37
        ///built on
        ///April 8, 2013
        ///
        ///Copyright © 2008-2013 Fuks Alexander.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CONF002 {
            get {
                return ResourceManager.GetString("CONF002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start automatically at Windows startup.
        /// </summary>
        internal static string CONF003 {
            get {
                return ResourceManager.GetString("CONF003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface.
        /// </summary>
        internal static string CONF004 {
            get {
                return ResourceManager.GetString("CONF004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string CONF005 {
            get {
                return ResourceManager.GetString("CONF005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic.
        /// </summary>
        internal static string CONF006 {
            get {
                return ResourceManager.GetString("CONF006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic limit for one week.
        /// </summary>
        internal static string CONF007 {
            get {
                return ResourceManager.GetString("CONF007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round up traffic values.
        /// </summary>
        internal static string CONF008 {
            get {
                return ResourceManager.GetString("CONF008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your position in top.
        /// </summary>
        internal static string CONF009 {
            get {
                return ResourceManager.GetString("CONF009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Tray.
        /// </summary>
        internal static string CONF010 {
            get {
                return ResourceManager.GetString("CONF010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Ranges: Exceed, Critical, Warning.
        /// </summary>
        internal static string CONF011 {
            get {
                return ResourceManager.GetString("CONF011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw digits on the icon.
        /// </summary>
        internal static string CONF012 {
            get {
                return ResourceManager.GetString("CONF012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon fashion.
        /// </summary>
        internal static string CONF013 {
            get {
                return ResourceManager.GetString("CONF013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string CONF014 {
            get {
                return ResourceManager.GetString("CONF014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use local cache to increase performance (recommended).
        /// </summary>
        internal static string CONF015 {
            get {
                return ResourceManager.GetString("CONF015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string CONF017 {
            get {
                return ResourceManager.GetString("CONF017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string CONF018 {
            get {
                return ResourceManager.GetString("CONF018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        internal static string CONF019 {
            get {
                return ResourceManager.GetString("CONF019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smile.
        /// </summary>
        internal static string CONF020 {
            get {
                return ResourceManager.GetString("CONF020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent.
        /// </summary>
        internal static string CONF021 {
            get {
                return ResourceManager.GetString("CONF021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits color.
        /// </summary>
        internal static string CONF022 {
            get {
                return ResourceManager.GetString("CONF022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use traffic filter.
        /// </summary>
        internal static string CONF023 {
            get {
                return ResourceManager.GetString("CONF023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What websites are already in filter?.
        /// </summary>
        internal static string CONF024 {
            get {
                return ResourceManager.GetString("CONF024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter&apos;s list is empty..
        /// </summary>
        internal static string CONF025 {
            get {
                return ResourceManager.GetString("CONF025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following websites are present in the filter&apos;s list:
        ///{0}.
        /// </summary>
        internal static string CONF026 {
            get {
                return ResourceManager.GetString("CONF026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter is turned off now..
        /// </summary>
        internal static string CONF027_removed {
            get {
                return ResourceManager.GetString("CONF027_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display everyday notification.
        /// </summary>
        internal static string CONF028 {
            get {
                return ResourceManager.GetString("CONF028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits size.
        /// </summary>
        internal static string CONF029 {
            get {
                return ResourceManager.GetString("CONF029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font name.
        /// </summary>
        internal static string CONF030 {
            get {
                return ResourceManager.GetString("CONF030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location.
        /// </summary>
        internal static string CONF031 {
            get {
                return ResourceManager.GetString("CONF031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berdyansk,Zaporozhye,Lviv,Sevastopol&apos;,Yalta.
        /// </summary>
        internal static string CONF032 {
            get {
                return ResourceManager.GetString("CONF032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
        /// 
        ///This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
        /// 
        ///You should have received a cop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COPYRIGHTTEXT {
            get {
                return ResourceManager.GetString("COPYRIGHTTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friday.
        /// </summary>
        internal static string FridayR {
            get {
                return ResourceManager.GetString("FridayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect local IP! Please specify it in parameters manually..
        /// </summary>
        internal static string INTERNAL_IP_NOTFOUND {
            get {
                return ResourceManager.GetString("INTERNAL_IP_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monday.
        /// </summary>
        internal static string MondayR {
            get {
                return ResourceManager.GetString("MondayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable images.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable images.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images inaccessable.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0 is already run..
        /// </summary>
        internal static string PROGRAM001 {
            get {
                return ResourceManager.GetString("PROGRAM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0.
        /// </summary>
        internal static string PROGRAMNAME {
            get {
                return ResourceManager.GetString("PROGRAMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to saturday.
        /// </summary>
        internal static string SaturdayR {
            get {
                return ResourceManager.GetString("SaturdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&amp;unday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunday.
        /// </summary>
        internal static string SundayR {
            get {
                return ResourceManager.GetString("SundayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic statistic for {0}.
        /// </summary>
        internal static string TA001 {
            get {
                return ResourceManager.GetString("TA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total used traffic: {0}.
        /// </summary>
        internal static string TA002 {
            get {
                return ResourceManager.GetString("TA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your position in top is {0} out of {1}.
        /// </summary>
        internal static string TA003 {
            get {
                return ResourceManager.GetString("TA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current week&apos;s statistics.
        /// </summary>
        internal static string TA004 {
            get {
                return ResourceManager.GetString("TA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be in TOP 10 this week.
        /// </summary>
        internal static string TA005 {
            get {
                return ResourceManager.GetString("TA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% chance to be in TOP 10 this week.
        /// </summary>
        internal static string TA006 {
            get {
                return ResourceManager.GetString("TA006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous week&apos;s statistics.
        /// </summary>
        internal static string TA007 {
            get {
                return ResourceManager.GetString("TA007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy address.
        /// </summary>
        internal static string TA008 {
            get {
                return ResourceManager.GetString("TA008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to filter.
        /// </summary>
        internal static string TA009 {
            get {
                return ResourceManager.GetString("TA009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total filtered traffic: {0}.
        /// </summary>
        internal static string TA010 {
            get {
                return ResourceManager.GetString("TA010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from filter.
        /// </summary>
        internal static string TA011 {
            get {
                return ResourceManager.GetString("TA011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total together: {1}.
        /// </summary>
        internal static string TA012 {
            get {
                return ResourceManager.GetString("TA012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occur during retrieving statistics. It can be network or server error. Statistics can be wrong or partially filled!.
        /// </summary>
        internal static string TA013 {
            get {
                return ResourceManager.GetString("TA013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        internal static string TAColumn1 {
            get {
                return ResourceManager.GetString("TAColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used traffic.
        /// </summary>
        internal static string TAColumn2 {
            get {
                return ResourceManager.GetString("TAColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string TAMENUABOUT {
            get {
                return ResourceManager.GetString("TAMENUABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Day.
        /// </summary>
        internal static string TAMENUDAY {
            get {
                return ResourceManager.GetString("TAMENUDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string TAMENUHELP {
            get {
                return ResourceManager.GetString("TAMENUHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Setup.
        /// </summary>
        internal static string TAMENUSETUP {
            get {
                return ResourceManager.GetString("TAMENUSETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Week.
        /// </summary>
        internal static string TAMENUWEEK {
            get {
                return ResourceManager.GetString("TAMENUWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Current week.
        /// </summary>
        internal static string TASUBMENUCURRWEEK {
            get {
                return ResourceManager.GetString("TASUBMENUCURRWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pr&amp;evious week.
        /// </summary>
        internal static string TASUBMENUPREVWEEK {
            get {
                return ResourceManager.GetString("TASUBMENUPREVWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T&amp;hursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thursday.
        /// </summary>
        internal static string ThursdayR {
            get {
                return ResourceManager.GetString("ThursdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tuesday.
        /// </summary>
        internal static string TuesdayR {
            get {
                return ResourceManager.GetString("TuesdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wednesday.
        /// </summary>
        internal static string WednesdayR {
            get {
                return ResourceManager.GetString("WednesdayR", resourceCulture);
            }
        }
    }
}
