//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traffic_Accounting.MultiLanguages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traffic_Accounting.MultiLanguages.LangRU", typeof(LangRU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0 сборка 41
        ///собрано
        ///7 июня 2014
        ///
        ///Все права защищены © 2008-2014 Фукс Александр.
        /// </summary>
        internal static string ABOUT {
            get {
                return ResourceManager.GetString("ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Б.
        /// </summary>
        internal static string B {
            get {
                return ResourceManager.GetString("B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основные.
        /// </summary>
        internal static string CONF002 {
            get {
                return ResourceManager.GetString("CONF002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запускать вместе с Windows.
        /// </summary>
        internal static string CONF003 {
            get {
                return ResourceManager.GetString("CONF003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string CONF005 {
            get {
                return ResourceManager.GetString("CONF005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Траффик.
        /// </summary>
        internal static string CONF006 {
            get {
                return ResourceManager.GetString("CONF006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лимит траффика на неделю.
        /// </summary>
        internal static string CONF007 {
            get {
                return ResourceManager.GetString("CONF007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Округлять значения траффика.
        /// </summary>
        internal static string CONF008 {
            get {
                return ResourceManager.GetString("CONF008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проверять позицию в ТОП.
        /// </summary>
        internal static string CONF009 {
            get {
                return ResourceManager.GetString("CONF009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системный лоток.
        /// </summary>
        internal static string CONF010 {
            get {
                return ResourceManager.GetString("CONF010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Границы траффика: Превышен, Критично, Предупреждение.
        /// </summary>
        internal static string CONF011 {
            get {
                return ResourceManager.GetString("CONF011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отображать цифры на иконке.
        /// </summary>
        internal static string CONF012 {
            get {
                return ResourceManager.GetString("CONF012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стиль иконки.
        /// </summary>
        internal static string CONF013 {
            get {
                return ResourceManager.GetString("CONF013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система.
        /// </summary>
        internal static string CONF014 {
            get {
                return ResourceManager.GetString("CONF014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать кэш для повышения производительности (рекомендуется).
        /// </summary>
        internal static string CONF015 {
            get {
                return ResourceManager.GetString("CONF015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квадрат.
        /// </summary>
        internal static string CONF017 {
            get {
                return ResourceManager.GetString("CONF017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Круг.
        /// </summary>
        internal static string CONF018 {
            get {
                return ResourceManager.GetString("CONF018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Треугольник.
        /// </summary>
        internal static string CONF019 {
            get {
                return ResourceManager.GetString("CONF019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Смайл.
        /// </summary>
        internal static string CONF020 {
            get {
                return ResourceManager.GetString("CONF020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прозрачный.
        /// </summary>
        internal static string CONF021 {
            get {
                return ResourceManager.GetString("CONF021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет цифр.
        /// </summary>
        internal static string CONF022 {
            get {
                return ResourceManager.GetString("CONF022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать фильтр.
        /// </summary>
        internal static string CONF023 {
            get {
                return ResourceManager.GetString("CONF023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какие вебсайты уже фильтруются?.
        /// </summary>
        internal static string CONF024 {
            get {
                return ResourceManager.GetString("CONF024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список фильтра пуст..
        /// </summary>
        internal static string CONF025 {
            get {
                return ResourceManager.GetString("CONF025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующие вебсайты присутствуют в списке фильтра:
        ///{0}.
        /// </summary>
        internal static string CONF026 {
            get {
                return ResourceManager.GetString("CONF026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показывать ежедневное уведомление.
        /// </summary>
        internal static string CONF028 {
            get {
                return ResourceManager.GetString("CONF028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Размер цифр.
        /// </summary>
        internal static string CONF029 {
            get {
                return ResourceManager.GetString("CONF029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шрифт.
        /// </summary>
        internal static string CONF030 {
            get {
                return ResourceManager.GetString("CONF030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        internal static string CONF031 {
            get {
                return ResourceManager.GetString("CONF031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бердянск,Днепропетровск,Запорожье,Львов,Севастополь,Ялта.
        /// </summary>
        internal static string CONF032 {
            get {
                return ResourceManager.GetString("CONF032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Писать лог в файл.
        /// </summary>
        internal static string CONF033 {
            get {
                return ResourceManager.GetString("CONF033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительные.
        /// </summary>
        internal static string CONF034 {
            get {
                return ResourceManager.GetString("CONF034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите имя машины:.
        /// </summary>
        internal static string CONFA001 {
            get {
                return ResourceManager.GetString("CONFA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите путь для получения статистики за день:.
        /// </summary>
        internal static string CONFA002 {
            get {
                return ResourceManager.GetString("CONFA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите путь для получения статистики за неделю:.
        /// </summary>
        internal static string CONFA003 {
            get {
                return ResourceManager.GetString("CONFA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите настройки обрезания для пропуска обработки излишних данных html:.
        /// </summary>
        internal static string CONFA004 {
            get {
                return ResourceManager.GetString("CONFA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите паттерн статистики траффика:.
        /// </summary>
        internal static string CONFA005 {
            get {
                return ResourceManager.GetString("CONFA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите паттерн для &quot;TOP10&quot;:.
        /// </summary>
        internal static string CONFA006 {
            get {
                return ResourceManager.GetString("CONFA006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить настройки.
        /// </summary>
        internal static string CONFA007 {
            get {
                return ResourceManager.GetString("CONFA007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string CONFA008 {
            get {
                return ResourceManager.GetString("CONFA008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эта программа является бесплатной; вы можете распрастранять её и/или изменять согласно с условиями лицензии GNU General Public Licanse, опубликованной фондом Free Software Foundation; лицензии версии 2 или (по вашему усмотрению) любой более поздней версии.
        ///
        ///Эта программа создана в надежде, что она может быть полезна, но БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ; даже без подразумеваемой гарантии ГОДНОСТИ или ПРИГОДНОСТИ ДЛЯ СПЕЦИФИЧЕСКОЙ ЦЕЛИ. Для дополнительной информации обращайтесь к тексту лицензии GNU General Public L [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string COPYRIGHTTEXT {
            get {
                return ResourceManager.GetString("COPYRIGHTTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось прочесть статистику. Попробовать еще раз?.
        /// </summary>
        internal static string ERR002 {
            get {
                return ResourceManager.GetString("ERR002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П&amp;ятница.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пятницу.
        /// </summary>
        internal static string FridayR {
            get {
                return ResourceManager.GetString("FridayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГБ.
        /// </summary>
        internal static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось определить локальный IP адрес! Пожалуйста, укажите его в параметрах вручную..
        /// </summary>
        internal static string INTERNAL_IP_NOTFOUND {
            get {
                return ResourceManager.GetString("INTERNAL_IP_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to КБ.
        /// </summary>
        internal static string KB {
            get {
                return ResourceManager.GetString("KB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to МБ.
        /// </summary>
        internal static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Понедельник.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to понедельник.
        /// </summary>
        internal static string MondayR {
            get {
                return ResourceManager.GetString("MondayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть.
        /// </summary>
        internal static string MT001 {
            get {
                return ResourceManager.GetString("MT001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        internal static string MT002 {
            get {
                return ResourceManager.GetString("MT002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкл. картинки.
        /// </summary>
        internal static string MT003 {
            get {
                return ResourceManager.GetString("MT003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выкл. картинки.
        /// </summary>
        internal static string MT004 {
            get {
                return ResourceManager.GetString("MT004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картинки недоступны.
        /// </summary>
        internal static string MT005 {
            get {
                return ResourceManager.GetString("MT005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0 уже запущен..
        /// </summary>
        internal static string PROGRAM001 {
            get {
                return ResourceManager.GetString("PROGRAM001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traffic Accounting 4.0.
        /// </summary>
        internal static string PROGRAMNAME {
            get {
                return ResourceManager.GetString("PROGRAMNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С&amp;уббота.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to субботу.
        /// </summary>
        internal static string SaturdayR {
            get {
                return ResourceManager.GetString("SaturdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Воскресенье.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to воскресенье.
        /// </summary>
        internal static string SundayR {
            get {
                return ResourceManager.GetString("SundayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика траффика за {0}.
        /// </summary>
        internal static string TA001 {
            get {
                return ResourceManager.GetString("TA001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего использовано: {0}.
        /// </summary>
        internal static string TA002 {
            get {
                return ResourceManager.GetString("TA002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша позиция в ТОП: {0} из {1}.
        /// </summary>
        internal static string TA003 {
            get {
                return ResourceManager.GetString("TA003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика за текущую неделю.
        /// </summary>
        internal static string TA004 {
            get {
                return ResourceManager.GetString("TA004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не попадёте в ТОП 10.
        /// </summary>
        internal static string TA005 {
            get {
                return ResourceManager.GetString("TA005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}% шансов попасть в ТОП 10.
        /// </summary>
        internal static string TA006 {
            get {
                return ResourceManager.GetString("TA006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика за прошлую неделю.
        /// </summary>
        internal static string TA007 {
            get {
                return ResourceManager.GetString("TA007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировать адрес.
        /// </summary>
        internal static string TA008 {
            get {
                return ResourceManager.GetString("TA008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить в фильтр.
        /// </summary>
        internal static string TA009 {
            get {
                return ResourceManager.GetString("TA009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Всего отфильтровано: {0}.
        /// </summary>
        internal static string TA010 {
            get {
                return ResourceManager.GetString("TA010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить из фильтра.
        /// </summary>
        internal static string TA011 {
            get {
                return ResourceManager.GetString("TA011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого вместе: {1}.
        /// </summary>
        internal static string TA012 {
            get {
                return ResourceManager.GetString("TA012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при получении статистики. Возможно ошибка сети или сервера. Статистика может быть неверной или не полной!.
        /// </summary>
        internal static string TA013 {
            get {
                return ResourceManager.GetString("TA013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вебсайт.
        /// </summary>
        internal static string TAColumn1 {
            get {
                return ResourceManager.GetString("TAColumn1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Затрачено траффика.
        /// </summary>
        internal static string TAColumn2 {
            get {
                return ResourceManager.GetString("TAColumn2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;О программе.
        /// </summary>
        internal static string TAMENUABOUT {
            get {
                return ResourceManager.GetString("TAMENUABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;День.
        /// </summary>
        internal static string TAMENUDAY {
            get {
                return ResourceManager.GetString("TAMENUDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Справка.
        /// </summary>
        internal static string TAMENUHELP {
            get {
                return ResourceManager.GetString("TAMENUHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Н&amp;астройки.
        /// </summary>
        internal static string TAMENUSETUP {
            get {
                return ResourceManager.GetString("TAMENUSETUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Неделя.
        /// </summary>
        internal static string TAMENUWEEK {
            get {
                return ResourceManager.GetString("TAMENUWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Текущая неделя.
        /// </summary>
        internal static string TASUBMENUCURRWEEK {
            get {
                return ResourceManager.GetString("TASUBMENUCURRWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Прошлая неделя.
        /// </summary>
        internal static string TASUBMENUPREVWEEK {
            get {
                return ResourceManager.GetString("TASUBMENUPREVWEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Четверг.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to четверг.
        /// </summary>
        internal static string ThursdayR {
            get {
                return ResourceManager.GetString("ThursdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Вторник.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вторник.
        /// </summary>
        internal static string TuesdayR {
            get {
                return ResourceManager.GetString("TuesdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Среда.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to среду.
        /// </summary>
        internal static string WednesdayR {
            get {
                return ResourceManager.GetString("WednesdayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в {0}.
        /// </summary>
        internal static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старт.
        /// </summary>
        internal static string WELCOMESTART {
            get {
                return ResourceManager.GetString("WELCOMESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в Traffic Accounting 4.0.
        ///
        ///Он позволяет с лёгкостью контролировать ваш расход траффика и быть в курсе текущего баланса. Вы сможете просматривать детальную статистику и получать уведомления. Просто задайте пару настроек и нажмите &apos;Старт&apos; чтобы начать пользоваться!.
        /// </summary>
        internal static string WELCOMETEXT {
            get {
                return ResourceManager.GetString("WELCOMETEXT", resourceCulture);
            }
        }
    }
}
